# -*- coding: utf-8 -*-
"""PI2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LX4XqJ_akMP_7q_BwNVSgXZ1I2s8dUpG

# Function to standardize superset data
"""

import pandas as pd
from datetime import datetime

def standardize_superset_data(raw_json):

    # 1. Extract metadata correctly
    metadata = {
        "dashboard_id": raw_json.get("metadata", {}).get("dashboard_id"),
        "chart_id": raw_json.get("metadata", {}).get("chart_id"),
        "filters": raw_json.get("query_context", {}).get("filters", [])
    }

    # 2. Extract tabular data
    rows = raw_json["result"][0]["data"]
    df = pd.DataFrame(rows)

    # 3. Mapping rules
    mapping = {
        "ds": "date",
        "vehicle_type_label": "vehicle_type",
        "value": "kpi_value",
        "metric": "kpi_name"
    }

    # 4. Apply mapping
    df = df.rename(columns=mapping)

    # 5. Type conversion
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")

    if "kpi_value" in df.columns:
        df["kpi_value"] = pd.to_numeric(df["kpi_value"], errors="coerce")

    # 6. Validate schema
    required = ["date", "kpi_value"]

    for col in required:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    # 7. Final standardized object
    standardized = {
        "metadata": metadata,
        "schema": {
            "date": "date",
            "category": "vehicle_type",
            "value": "kpi_value"
        },
        "data": df.to_dict(orient="records")
    }

    return standardized

import json

with open("sample.json", "r") as f:
    data = json.load(f)

output = standardize_superset_data(data)

print(output)